### ISSUE TITLE
[front/error] 상세페이지 해상도 축소 시 모달창이 계속 내려옴

### ISSUE THREAD

**Issue by nagosu** [SV-Summer-BootCamp-TeamJ/2023SB-Team-J#35]
## 🤔 오류 내용
  상세페이지 해상도 축소 시 모달창이 계속 내려옴
<br>

## ⚠ 에러 캡쳐 

https://github.com/2023SB-TeamJ/2023SB-Team-J/assets/100352367/50437abc-13b3-490b-bc2b-f4b6a93bb76d

<br>

**Comment by sunjae98** [comment]
이게 무슨 일이야
